require "eyu.settings"
require "eyu.keymaps"
require "eyu.plugins"
require "eyu.colorscheme"

require "eyu.cmp"
require "eyu.mason"
require "eyu.telescope"
require "eyu.tree"
require "eyu.treesitter"
require "eyu.indent"
